language: r
cache: packages
dist: trusty

branches:
  only:
  - master

jobs:
  include:
  - r: 3.3
  - r: 3.4
  - r: release
  - r: devel
  - os: osx
  
compiler:
  - gcc
  - clang

before_install:
 - export LD_LIBRARY_PATH=$(if [[ $CC == "clang" ]]; then echo -n '/usr/local/clang/lib'; fi)

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE