language: r
cache: packages
dist: trusty

jobs:
  include:
  - r: devel
  - r: 3.3
  - r: 3.4
  - r: release
  - os: osx
  
compiler:
  - gcc
  - clang
  
branches:
  only:
  - master
  
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE